'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const C=require('../web/core.js'),root=path.resolve(__dirname,'..');
const data=n=>JSON.parse(fs.readFileSync(path.join(root,'data',n+'.json'),'utf8'));
let passed=0;function test(name,f){try{f();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name);throw e;}}
const cp=C.clone;
const d=C.DEFAULTS;
test('kg-tonne normalized equivalence',()=>{const r=C.alignment(d.alignment);assert.equal(r.baseline.status,'mismatch');assert.equal(r.revision.status,'equivalent');});
test('currency change retained',()=>{const i=cp(d.alignment);i.right.currency='VND';assert.deepEqual(C.alignment(i).revision.differences,['currency']);});
test('purpose change retained and ablated',()=>{const i=cp(d.alignment);i.right.purpose='send';assert.equal(C.alignment(i).revision.status,'mismatch');assert.equal(C.alignment(i,{ignorePurpose:true}).revision.status,'equivalent');});
test('entity mismatch',()=>{const i=cp(d.alignment);i.right.entity='another';assert(C.alignment(i).revision.differences.includes('entity'));});
test('unknown unit unresolved',()=>{const i=cp(d.alignment);i.right.unit='crate';assert.equal(C.alignment(i).revision.status,'unresolved');});
test('dimension mismatch',()=>{const i=cp(d.alignment);i.right.unit='l';assert(C.alignment(i).revision.differences.includes('dimension'));});
test('quantity mismatch',()=>{const i=cp(d.alignment);i.right.quantity=2;assert(C.alignment(i).revision.differences.includes('quantity'));});
for(const [u,q]of [['g',1000000],['t',1],['吨',1],['tấn',1],['公斤',1000]])test('unit alias '+u,()=>{const i=cp(d.alignment);i.right.unit=u;i.right.quantity=q;assert.equal(C.alignment(i).revision.status,'equivalent');});
for(const val of [NaN,Infinity,-1,'1',null,true])test('invalid quantity '+String(val),()=>{const i=cp(d.alignment);i.right.quantity=val;assert.throws(()=>C.alignment(i));});
test('normalized overflow rejected',()=>{const i=cp(d.alignment);i.right.quantity=1e308;assert.throws(()=>C.alignment(i));});
test('3-No conflict not averaged away',()=>{const r=C.threeNo(d['three-no']);assert.equal(r.baseline.status,'within-target');assert.equal(r.revision.status,'conflict');assert.equal(r.revision.missing.length,1);assert.equal(r.revision.intersection,null);});
test('consistent intervals',()=>{const r=C.threeNo({observations:[{low:2,high:4},{low:3,high:5}],target:{low:2,high:8}});assert.deepEqual(r.revision.intersection,[3,4]);assert.equal(r.revision.status,'within-target');});
test('missing-only insufficient',()=>assert.equal(C.threeNo({observations:[{}],target:{low:2,high:8}}).revision.status,'insufficient'));
test('incomplete observations retained',()=>assert.equal(C.threeNo({observations:[{low:2,high:3},{}],target:{low:2,high:8}}).revision.status,'incomplete'));
test('boundary intersection valid',()=>assert.deepEqual(C.threeNo({observations:[{low:2,high:3},{low:3,high:4}],target:{low:2,high:8}}).revision.intersection,[3,3]));
test('outside target',()=>assert.equal(C.threeNo({observations:[{low:9,high:10}],target:{low:2,high:8}}).revision.status,'outside-target'));
test('uncertain target',()=>assert.equal(C.threeNo({observations:[{low:1,high:10}],target:{low:2,high:8}}).revision.status,'uncertain'));
test('reversed input rejects',()=>assert.throws(()=>C.threeNo({observations:[{low:4,high:2}],target:{low:2,high:8}})));
test('reversed target rejects',()=>assert.throws(()=>C.threeNo({observations:[],target:{low:8,high:2}})));
test('too many intervals rejects',()=>assert.throws(()=>C.threeNo({observations:Array(101).fill({}),target:{low:2,high:8}})));
test('purpose-action retains useful draft',()=>{const r=C.action(d.action);assert.equal(r.revision.status,'review');assert.equal(r.revision.helpful_next,'prepare-draft');});
test('keyword overblocking visible',()=>{const i=cp(d.action);i.allowed_actions.push('send');const r=C.action(i);assert.equal(r.baseline.status,'review');assert.equal(r.revision.status,'allow');});
test('draft without evidence flagged',()=>{const i=cp(d.action);i.action='draft';i.evidence_count=0;assert(C.action(i).revision.failed.includes('evidence'));});
test('purpose action ablation',()=>{const i=cp(d.action);i.action='draft';i.observed_purpose='another';assert.equal(C.action(i).revision.status,'review');assert.equal(C.action(i,{ignorePurpose:true}).revision.status,'allow');});
test('unsupported action rejected',()=>assert.throws(()=>C.action({...d.action,action:'pay'})));
test('fractional evidence rejected',()=>assert.throws(()=>C.action({...d.action,evidence_count:.1})));
test('route goals change selection',()=>assert.notDeepEqual(C.route({...d.purpose,goal:'speed'}).revision.chosen.path,C.route(d.purpose).revision.chosen.path));
test('route preserves alternatives',()=>assert(C.route(d.purpose).revision.alternatives.length>1));
test('same-node zero route',()=>assert.equal(C.route({from:'D',to:'D'}).revision.chosen.cost,0));
test('bad route node rejected',()=>assert.throws(()=>C.route({from:'X'})));
test('unknown lab rejected',()=>assert.throws(()=>C.runLab('hack',{})));
const catalog=data('catalog'),lessons=data('lessons'),concepts=data('concepts'),locales=data('locales');
test('483 unique candidates',()=>{assert.equal(catalog.repositories.length,483);assert.equal(new Set(catalog.repositories.map(r=>r.name)).size,483);});
test('48 curated routes',()=>assert.equal(catalog.repositories.filter(r=>r.featured).length,48));
test('13 locale schema complete',()=>{assert.equal(Object.keys(locales).length,13);for(const l of Object.values(locales))assert.deepEqual(Object.keys(l).sort(),Object.keys(locales.en).sort());});
for(const lang of ['zh','en','vi'])test('all 12 full lessons '+lang,()=>{assert.equal(lessons.length,12);for(const l of lessons){for(const f of ['body','question','example','misconception','practice'])assert(l[f][lang]?.length>10);assert.equal(l.quiz.options[lang].length,3);assert(l.quiz.explanation[lang]);}});
for(const word of ['教育','education','giáo dục','pendidikan','การศึกษา','ပညာရေး','ການສຶກສາ','ការអប់រំ'])test('multilingual concept '+word,()=>assert(C.findConcepts(word,concepts).includes('education')));
test('exact known repo first',()=>{const name='DIKWP-PACT-v0.1.0';assert.equal(C.rankRepositories(name,catalog.repositories,concepts)[0].name,name);});
test('license filter not fabricated',()=>assert(C.rankRepositories('education',catalog.repositories,concepts,{licensed:true}).every(r=>r.license)));
test('curated filter',()=>assert.equal(C.rankRepositories('',catalog.repositories,concepts,{featured:true}).length,48));
test('recommendation reasons present',()=>assert(C.rankRepositories('giáo dục',catalog.repositories,concepts)[0].hits.includes('education')));
test('prerequisites precede dependents',()=>{const r=C.learningRoute(lessons,['innovation']);r.forEach((l,i)=>l.prerequisites.forEach(p=>assert(r.findIndex(a=>a.id===p)<i)));});
test('cyclic learning routes rejected',()=>assert.throws(()=>C.learningRoute([{id:'a',tags:['x'],prerequisites:['b']},{id:'b',tags:[],prerequisites:['a']}],['x'])));
test('no concept defaults to DIKWP',()=>assert.equal(C.learningRoute(lessons,[])[0].id,'dikwp'));
for(const l of lessons)test('quiz '+l.id,()=>{assert(C.checkQuiz(l,l.quiz.answer).correct);assert(!C.checkQuiz(l,(l.quiz.answer+1)%3).correct);assert.throws(()=>C.checkQuiz(l,8));});
let p=C.newProject();p.title='中越产品语义核对';p.problem='Compare cross-language product data';p.purpose='Understand and compare';p.inherited='DIKWP typed resources';p.changed='Contextual unit comparison';p.hypothesis='Normalization resolves equivalent units without hiding currency differences';p.reflection='Unknown units still need human definition';p.repositories=[{name:'DIKWP-PACT-v0.1.0',url:'https://github.com/YucongDuan/DIKWP-PACT-v0.1.0',role:'purpose check',license:'Apache-2.0'}];p.runs=[{lab:'alignment',input:cp(d.alignment),output:C.alignment(d.alignment),at:'2026-09-16T00:00:00Z',engine:'1.0.0'}];
test('project roundtrip',()=>assert.equal(C.validateProject(JSON.parse(JSON.stringify(p))).title,p.title));
test('invalid source rejected',()=>{const a=cp(p);a.repositories[0].url='https://evil.invalid';assert.throws(()=>C.validateProject(a));});
test('more than six components rejected',()=>assert.throws(()=>C.validateProject({...p,repositories:Array(7).fill(p.repositories[0])})));
test('blank title rejected',()=>assert.throws(()=>C.validateProject({...p,title:''})));
test('malformed experiment rejected',()=>assert.throws(()=>C.validateProject({...p,runs:[{}]})));
test('oversized text rejected',()=>assert.throws(()=>C.validateProject({...p,problem:'x'.repeat(20001)})));
test('manifest requires pin until provided',()=>assert.equal(C.makeManifest(p).repositories[0].status,'pin-required'));
test('project source metadata no source implementation claim',()=>assert(C.scaffold(p)['README.md'].includes('not copied upstream code')));
test('scaffold runnable files complete',()=>{const f=C.scaffold(p);for(const n of ['experiment.py','tests/test_experiment.py','data/input.json','upstream.lock.json','ADAPTATION.md'])assert(f[n]);});
const sample=path.join(root,'examples','cross_language_trade');fs.mkdirSync(sample,{recursive:true});const out=C.scaffold(p);out['LICENSE']=fs.readFileSync(path.join(root,'LICENSE'),'utf8');out['NOTICE']='New teaching scaffold; foundations and upstream choices: Yucong Duan.\n';Object.entries(out).forEach(([n,s])=>{const f=path.join(sample,n);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,s);});fs.writeFileSync(path.join(root,'examples','cross_language_trade.zip'),C.zipFiles(out));
test('ZIP header correct',()=>assert.equal(Buffer.from(C.zipFiles({'你好.txt':'越南 Việt Nam'})).readUInt32LE(0),0x04034b50));
fs.writeFileSync(path.join(root,'qa/core-results.json'),JSON.stringify({suite:'node-core',passed,failed:0},null,2));console.log('TOTAL '+passed+' passed');
