from pathlib import Path
import json
R=Path(__file__).resolve().parents[1]
keys='home learn compass labs studio classroom library hero start explore problem recommend search all featured compare add remove open source license level selected purpose data information knowledge wisdom run save export import reset title beneficiary constraints inherited changed hypothesis evidence reflection project create results baseline variant difference reading quiz check explanation prerequisites progress glossary language offline account login register logout username password course join code submit feedback back next empty saved error copy report settings'.split()
rows={
'zh':('简体中文','知行共创 · 中国—东盟版','从理解一个方法，到创造自己的答案。','学习段玉聪的DIKWP、语义数学与人工意识方法，选择开放项目，用可修改实验把问题变成作品。',
'启航|学习地图|仓库罗盘|实践实验室|作品工作室|师生共创|研究资料|从理解到创造|开始学习|探索仓库|我的问题|推荐路径|搜索|全部|精选入口|对比|加入|移除|打开|来源|许可|基础|已选择|目的 P|数据 D|信息 I|知识 K|智慧 W|运行实验|保存|导出|导入|重置|标题|受益者|条件与约束|继承了什么|改变了什么|创新假设|支持证据|反思与下一问题|作品|创建|结果|基线|改进方案|差异|研读|自测|检查答案|解释|建议先学|学习进展|术语桥|语言|离线可用|账户|登录|注册|退出|用户名|密码|课程|加入课程|加入码|提交作品|反馈|返回|下一步|暂无记录|已保存|操作未完成|复制|报告导读|设置'),
'en':('English','OpenStudio · China–ASEAN Edition','Understand a method. Create your own answer.','Learn Yucong Duan’s DIKWP, semantic mathematics and artificial-consciousness methods. Choose open projects and turn questions into working experiments.',
'Launchpad|Learning atlas|Repository compass|Practice labs|Project studio|Learning together|Research library|From understanding to creation|Start learning|Explore repositories|My problem|Recommend a route|Search|All|Featured|Compare|Add|Remove|Open|Source|License|Experience|Selected|Purpose P|Data D|Information I|Knowledge K|Wisdom W|Run experiment|Save|Export|Import|Reset|Title|Beneficiary|Conditions and constraints|What I inherited|What I changed|Innovation hypothesis|Supporting evidence|Reflection and next question|Project|Create|Results|Baseline|Revision|Difference|Read|Self-check|Check answer|Explanation|Suggested prerequisites|Learning progress|Terminology bridge|Language|Offline ready|Account|Sign in|Register|Sign out|Username|Password|Course|Join course|Join code|Submit project|Feedback|Back|Next|No records yet|Saved|Action not completed|Copy|Report reader|Settings'),
'vi':('Tiếng Việt','OpenStudio · Trung Quốc–ASEAN','Hiểu một phương pháp. Tạo câu trả lời của riêng bạn.','Học DIKWP, toán học ngữ nghĩa và phương pháp nghiên cứu ý thức nhân tạo của Yucong Duan. Chọn kho mã mở, thử nghiệm và phát triển giải pháp của bạn.',
'Khởi đầu|Bản đồ học tập|La bàn kho mã|Phòng thực hành|Xưởng dự án|Cùng học tập|Thư viện nghiên cứu|Từ hiểu biết đến sáng tạo|Bắt đầu học|Khám phá kho mã|Vấn đề của tôi|Gợi ý lộ trình|Tìm kiếm|Tất cả|Nổi bật|So sánh|Thêm|Xóa|Mở|Nguồn|Giấy phép|Kinh nghiệm|Đã chọn|Mục đích P|Dữ liệu D|Thông tin I|Tri thức K|Trí tuệ W|Chạy thử nghiệm|Lưu|Xuất|Nhập|Đặt lại|Tiêu đề|Người hưởng lợi|Điều kiện và ràng buộc|Phần tôi kế thừa|Phần tôi thay đổi|Giả thuyết đổi mới|Bằng chứng hỗ trợ|Suy ngẫm và câu hỏi tiếp theo|Dự án|Tạo|Kết quả|Cơ sở so sánh|Bản cải tiến|Khác biệt|Đọc|Tự kiểm tra|Kiểm tra đáp án|Giải thích|Kiến thức nên học trước|Tiến độ học tập|Cầu nối thuật ngữ|Ngôn ngữ|Dùng ngoại tuyến|Tài khoản|Đăng nhập|Đăng ký|Đăng xuất|Tên người dùng|Mật khẩu|Khóa học|Tham gia khóa học|Mã tham gia|Nộp dự án|Phản hồi|Quay lại|Tiếp theo|Chưa có bản ghi|Đã lưu|Chưa hoàn tất thao tác|Sao chép|Đọc báo cáo|Cài đặt'),
'id':('Bahasa Indonesia','OpenStudio · Tiongkok–ASEAN','Pahami metodenya. Ciptakan jawaban Anda sendiri.','Pelajari DIKWP, matematika semantik, dan metode kesadaran buatan Yucong Duan. Pilih repositori terbuka, lakukan eksperimen, lalu kembangkan solusi Anda.',
'Beranda|Peta belajar|Kompas repositori|Laboratorium praktik|Studio proyek|Belajar bersama|Pustaka riset|Dari pemahaman ke penciptaan|Mulai belajar|Jelajahi repositori|Masalah saya|Sarankan jalur|Cari|Semua|Pilihan|Bandingkan|Tambah|Hapus|Buka|Sumber|Lisensi|Pengalaman|Dipilih|Tujuan P|Data D|Informasi I|Pengetahuan K|Kebijaksanaan W|Jalankan eksperimen|Simpan|Ekspor|Impor|Atur ulang|Judul|Penerima manfaat|Kondisi dan batasan|Yang saya warisi|Yang saya ubah|Hipotesis inovasi|Bukti pendukung|Refleksi dan pertanyaan berikutnya|Proyek|Buat|Hasil|Acuan|Revisi|Perbedaan|Baca|Uji mandiri|Periksa jawaban|Penjelasan|Prasyarat yang disarankan|Kemajuan belajar|Jembatan istilah|Bahasa|Siap luring|Akun|Masuk|Daftar|Keluar|Nama pengguna|Kata sandi|Kelas|Gabung kelas|Kode gabung|Kirim proyek|Umpan balik|Kembali|Berikutnya|Belum ada catatan|Tersimpan|Tindakan belum selesai|Salin|Pembaca laporan|Pengaturan'),
'ms':('Bahasa Melayu','OpenStudio · China–ASEAN','Fahami kaedah. Cipta jawapan anda sendiri.','Pelajari DIKWP, matematik semantik dan kaedah kesedaran buatan Yucong Duan. Pilih repositori terbuka, jalankan eksperimen dan bina penyelesaian anda.',
'Laman utama|Peta pembelajaran|Kompas repositori|Makmal amali|Studio projek|Belajar bersama|Perpustakaan penyelidikan|Daripada pemahaman kepada penciptaan|Mula belajar|Teroka repositori|Masalah saya|Cadangkan laluan|Cari|Semua|Pilihan|Bandingkan|Tambah|Buang|Buka|Sumber|Lesen|Pengalaman|Dipilih|Tujuan P|Data D|Maklumat I|Pengetahuan K|Kebijaksanaan W|Jalankan eksperimen|Simpan|Eksport|Import|Set semula|Tajuk|Penerima manfaat|Syarat dan kekangan|Yang saya warisi|Yang saya ubah|Hipotesis inovasi|Bukti sokongan|Refleksi dan soalan seterusnya|Projek|Cipta|Keputusan|Garis dasar|Semakan|Perbezaan|Baca|Ujian kendiri|Semak jawapan|Penjelasan|Prasyarat dicadangkan|Kemajuan pembelajaran|Jambatan istilah|Bahasa|Sedia luar talian|Akaun|Log masuk|Daftar|Log keluar|Nama pengguna|Kata laluan|Kursus|Sertai kursus|Kod penyertaan|Hantar projek|Maklum balas|Kembali|Seterusnya|Belum ada rekod|Disimpan|Tindakan belum selesai|Salin|Pembaca laporan|Tetapan'),
'pt':('Português','OpenStudio · China–ASEAN','Compreenda um método. Crie a sua própria resposta.','Aprenda DIKWP, matemática semântica e métodos de consciência artificial de Yucong Duan. Escolha repositórios abertos, experimente e desenvolva soluções.',
'Início|Mapa de aprendizagem|Bússola de repositórios|Laboratórios|Estúdio de projetos|Aprender em conjunto|Biblioteca de investigação|Da compreensão à criação|Começar a aprender|Explorar repositórios|O meu problema|Sugerir percurso|Pesquisar|Todos|Destaques|Comparar|Adicionar|Remover|Abrir|Fonte|Licença|Experiência|Selecionados|Propósito P|Dados D|Informação I|Conhecimento K|Sabedoria W|Executar experiência|Guardar|Exportar|Importar|Repor|Título|Beneficiário|Condições e restrições|O que herdei|O que alterei|Hipótese de inovação|Evidência de apoio|Reflexão e próxima pergunta|Projeto|Criar|Resultados|Referência|Revisão|Diferença|Ler|Autoavaliação|Verificar resposta|Explicação|Pré-requisitos sugeridos|Progresso de aprendizagem|Ponte terminológica|Idioma|Disponível sem ligação|Conta|Entrar|Registar|Sair|Utilizador|Palavra-passe|Curso|Aderir ao curso|Código de acesso|Submeter projeto|Comentários|Voltar|Seguinte|Sem registos|Guardado|Ação não concluída|Copiar|Leitor de relatório|Definições'),
'fil':('Filipino','OpenStudio · Tsina–ASEAN','Unawain ang pamamaraan. Lumikha ng sariling sagot.','Pag-aralan ang DIKWP, semantikong matematika at artipisyal na kamalayan ni Yucong Duan. Pumili ng bukas na repositoryo at bumuo ng solusyon sa pamamagitan ng eksperimento.',
'Simula|Mapa ng pag-aaral|Gabay sa repositoryo|Laboratoryo|Studio ng proyekto|Sama-samang pag-aaral|Aklatan ng pananaliksik|Mula pag-unawa tungo sa paglikha|Magsimulang matuto|Tuklasin ang mga repositoryo|Aking suliranin|Magmungkahi ng landas|Maghanap|Lahat|Tampok|Ihambing|Idagdag|Alisin|Buksan|Pinagmulan|Lisensya|Karanasan|Napili|Layunin P|Datos D|Impormasyon I|Kaalaman K|Karunungan W|Patakbuhin ang eksperimento|I-save|I-export|I-import|I-reset|Pamagat|Makikinabang|Mga kondisyon at limitasyon|Aking minana|Aking binago|Palagay sa inobasyon|Sumusuportang ebidensya|Pagninilay at susunod na tanong|Proyekto|Lumikha|Mga resulta|Batayan|Pagbabago|Pagkakaiba|Basahin|Sariling pagsusulit|Suriin ang sagot|Paliwanag|Mungkahing paunang aralin|Pag-unlad sa pag-aaral|Tulay ng mga termino|Wika|Magagamit nang offline|Account|Mag-sign in|Magrehistro|Mag-sign out|Username|Password|Kurso|Sumali sa kurso|Code sa pagsali|Ipasa ang proyekto|Puna|Bumalik|Susunod|Wala pang tala|Na-save|Hindi nakumpleto|Kopyahin|Babasahin ng ulat|Mga setting'),
 'th':('ไทย','OpenStudio · จีน–อาเซียน','เข้าใจวิธีการ สร้างคำตอบของคุณเอง','เรียนรู้ DIKWP คณิตศาสตร์เชิงความหมาย และวิธีศึกษาจิตสำนึกประดิษฐ์ของ Yucong Duan เลือกคลังโค้ด ทดลอง และพัฒนาแนวทางแก้ปัญหาของคุณ',
'หน้าหลัก|แผนที่การเรียนรู้|เข็มทิศคลังโค้ด|ห้องปฏิบัติการ|สตูดิโอโครงงาน|เรียนรู้ร่วมกัน|คลังงานวิจัย|จากความเข้าใจสู่การสร้างสรรค์|เริ่มเรียน|สำรวจคลังโค้ด|ปัญหาของฉัน|แนะนำเส้นทาง|ค้นหา|ทั้งหมด|รายการแนะนำ|เปรียบเทียบ|เพิ่ม|ลบ|เปิด|แหล่งที่มา|สัญญาอนุญาต|ประสบการณ์|ที่เลือก|จุดประสงค์ P|ข้อมูล D|สารสนเทศ I|ความรู้ K|ปัญญา W|เริ่มการทดลอง|บันทึก|ส่งออก|นำเข้า|รีเซ็ต|ชื่อเรื่อง|ผู้ได้รับประโยชน์|เงื่อนไขและข้อจำกัด|สิ่งที่สืบทอด|สิ่งที่เปลี่ยนแปลง|สมมติฐานนวัตกรรม|หลักฐานสนับสนุน|การสะท้อนคิดและคำถามถัดไป|โครงงาน|สร้าง|ผลลัพธ์|ค่าฐาน|ฉบับปรับปรุง|ความแตกต่าง|อ่าน|ทดสอบตนเอง|ตรวจคำตอบ|คำอธิบาย|พื้นฐานที่แนะนำ|ความก้าวหน้าการเรียน|สะพานคำศัพท์|ภาษา|พร้อมใช้งานออฟไลน์|บัญชี|เข้าสู่ระบบ|ลงทะเบียน|ออกจากระบบ|ชื่อผู้ใช้|รหัสผ่าน|รายวิชา|เข้าร่วมรายวิชา|รหัสเข้าร่วม|ส่งโครงงาน|ข้อเสนอแนะ|ย้อนกลับ|ถัดไป|ยังไม่มีข้อมูล|บันทึกแล้ว|ดำเนินการไม่สำเร็จ|คัดลอก|อ่านรายงาน|การตั้งค่า'),
 'km':('ភាសាខ្មែរ','OpenStudio · ចិន–អាស៊ាន','យល់ពីវិធីសាស្ត្រ បង្កើតចម្លើយរបស់អ្នក','សិក្សា DIKWP គណិតវិទ្យាអត្ថន័យ និងវិធីសាស្ត្រមនសិការសិប្បនិម្មិតរបស់ Yucong Duan។ ជ្រើសរើសឃ្លាំងកូដបើកចំហ សាកល្បង និងបង្កើតដំណោះស្រាយ។',
'ទំព័រដើម|ផែនទីសិក្សា|មគ្គុទ្ទេសក៍ឃ្លាំងកូដ|មន្ទីរពិសោធន៍|ស្ទូឌីយោគម្រោង|សិក្សារួមគ្នា|បណ្ណាល័យស្រាវជ្រាវ|ពីការយល់ដល់ការបង្កើត|ចាប់ផ្តើមសិក្សា|ស្វែងរកឃ្លាំងកូដ|បញ្ហារបស់ខ្ញុំ|ណែនាំផ្លូវ|ស្វែងរក|ទាំងអស់|ជម្រើសសំខាន់|ប្រៀបធៀប|បន្ថែម|ដកចេញ|បើក|ប្រភព|អាជ្ញាបណ្ណ|បទពិសោធន៍|បានជ្រើស|គោលបំណង P|ទិន្នន័យ D|ព័ត៌មាន I|ចំណេះដឹង K|ប្រាជ្ញា W|ដំណើរការពិសោធន៍|រក្សាទុក|នាំចេញ|នាំចូល|កំណត់ឡើងវិញ|ចំណងជើង|អ្នកទទួលផល|លក្ខខណ្ឌនិងកម្រិត|អ្វីដែលខ្ញុំទទួលបន្ត|អ្វីដែលខ្ញុំកែប្រែ|សម្មតិកម្មនវានុវត្តន៍|ភស្តុតាងគាំទ្រ|ការឆ្លុះបញ្ចាំងនិងសំណួរបន្ទាប់|គម្រោង|បង្កើត|លទ្ធផល|មូលដ្ឋាន|កំណែកែលម្អ|ភាពខុសគ្នា|អាន|តេស្តខ្លួនឯង|ពិនិត្យចម្លើយ|ការពន្យល់|ចំណេះដឹងមុនដែលណែនាំ|វឌ្ឍនភាពសិក្សា|ស្ពានពាក្យបច្ចេកទេស|ភាសា|ប្រើក្រៅបណ្ដាញ|គណនី|ចូល|ចុះឈ្មោះ|ចាកចេញ|ឈ្មោះអ្នកប្រើ|ពាក្យសម្ងាត់|វគ្គសិក្សា|ចូលរួមវគ្គ|កូដចូលរួម|ដាក់ស្នើគម្រោង|មតិយោបល់|ត្រឡប់|បន្ទាប់|មិនទាន់មានកំណត់ត្រា|បានរក្សាទុក|មិនទាន់បញ្ចប់|ចម្លង|អានរបាយការណ៍|ការកំណត់'),
 'lo':('ພາສາລາວ','OpenStudio · ຈີນ–ອາຊຽນ','ເຂົ້າໃຈວິທີການ ສ້າງຄຳຕອບຂອງທ່ານ','ຮຽນຮູ້ DIKWP ຄະນິດສາດຄວາມໝາຍ ແລະວິທີສຶກສາສະຕິປັນຍາປະດິດຂອງ Yucong Duan. ເລືອກຄັງລະຫັດ ທົດລອງ ແລະສ້າງທາງແກ້ໄຂ.',
'ໜ້າຫຼັກ|ແຜນທີ່ການຮຽນ|ເຂັມທິດຄັງລະຫັດ|ຫ້ອງທົດລອງ|ສະຕູດິໂອໂຄງການ|ຮຽນຮູ້ຮ່ວມກັນ|ຫ້ອງສະໝຸດວິຈັຍ|ຈາກຄວາມເຂົ້າໃຈສູ່ການສ້າງ|ເລີ່ມຮຽນ|ສຳຫຼວດຄັງລະຫັດ|ບັນຫາຂອງຂ້ອຍ|ແນະນຳເສັ້ນທາງ|ຄົ້ນຫາ|ທັງໝົດ|ລາຍການແນະນຳ|ປຽບທຽບ|ເພີ່ມ|ເອົາອອກ|ເປີດ|ແຫຼ່ງທີ່ມາ|ໃບອະນຸຍາດ|ປະສົບການ|ເລືອກແລ້ວ|ເປົ້າໝາຍ P|ຂໍ້ມູນ D|ສາລະສົນເທດ I|ຄວາມຮູ້ K|ປັນຍາ W|ເລີ່ມທົດລອງ|ບັນທຶກ|ສົ່ງອອກ|ນຳເຂົ້າ|ຕັ້ງໃໝ່|ຫົວຂໍ້|ຜູ້ໄດ້ຮັບຜົນ|ເງື່ອນໄຂແລະຂໍ້ຈຳກັດ|ສິ່ງທີ່ສືບທອດ|ສິ່ງທີ່ປ່ຽນແປງ|ສົມມຸດຖານນະວັດຕະກຳ|ຫຼັກຖານສະໜັບສະໜູນ|ການສະທ້ອນແລະຄຳຖາມຕໍ່ໄປ|ໂຄງການ|ສ້າງ|ຜົນໄດ້ຮັບ|ຄ່າພື້ນຖານ|ສະບັບປັບປຸງ|ຄວາມຕ່າງ|ອ່ານ|ທົດສອບຕົນເອງ|ກວດຄຳຕອບ|ຄຳອະທິບາຍ|ພື້ນຖານທີ່ແນະນຳ|ຄວາມກ້າວໜ້າ|ຂົວຄຳສັບ|ພາສາ|ໃຊ້ອອບລາຍ|ບັນຊີ|ເຂົ້າລະບົບ|ລົງທະບຽນ|ອອກຈາກລະບົບ|ຊື່ຜູ້ໃຊ້|ລະຫັດຜ່ານ|ຫຼັກສູດ|ເຂົ້າຮ່ວມ|ລະຫັດເຂົ້າຮ່ວມ|ສົ່ງໂຄງການ|ຄຳຄິດເຫັນ|ກັບຄືນ|ຕໍ່ໄປ|ຍັງບໍ່ມີບັນທຶກ|ບັນທຶກແລ້ວ|ຍັງບໍ່ສຳເລັດ|ສຳເນົາ|ອ່ານລາຍງານ|ຕັ້ງຄ່າ'),
 'my':('မြန်မာ','OpenStudio · တရုတ်–အာဆီယံ','နည်းလမ်းကို နားလည်ပြီး ကိုယ်ပိုင်အဖြေ ဖန်တီးပါ','Yucong Duan ၏ DIKWP၊ အဓိပ္ပာယ်ဆိုင်ရာ သင်္ချာနှင့် စက်အသိစိတ် သုတေသနနည်းလမ်းများကို လေ့လာပါ။ ကုဒ်သိုလှောင်ရုံကို ရွေးချယ်၍ စမ်းသပ်ပြီး ကိုယ်ပိုင်ဖြေရှင်းချက် ဖန်တီးပါ။',
'အစ|သင်ယူမှုမြေပုံ|ကုဒ်လမ်းညွှန်|စမ်းသပ်ခန်း|စီမံကိန်းစတူဒီယို|အတူလေ့လာခြင်း|သုတေသနစာကြည့်တိုက်|နားလည်မှုမှ ဖန်တီးမှုသို့|စတင်လေ့လာ|ကုဒ်ရှာဖွေ|ကျွန်ုပ်၏ပြဿနာ|လမ်းကြောင်းအကြံပြု|ရှာဖွေ|အားလုံး|ရွေးချယ်ထားသည်|နှိုင်းယှဉ်|ထည့်|ဖယ်ရှား|ဖွင့်|ရင်းမြစ်|လိုင်စင်|အတွေ့အကြုံ|ရွေးထားသည်|ရည်ရွယ်ချက် P|ဒေတာ D|သတင်းအချက်အလက် I|အသိပညာ K|ပညာဉာဏ် W|စမ်းသပ်မှုလုပ်ဆောင်|သိမ်းဆည်း|ထုတ်ယူ|တင်သွင်း|ပြန်သတ်မှတ်|ခေါင်းစဉ်|အကျိုးခံစားသူ|အခြေအနေနှင့်ကန့်သတ်ချက်|ဆက်ခံထားသောအပိုင်း|ပြောင်းလဲထားသောအပိုင်း|ဆန်းသစ်မှုယူဆချက်|ထောက်ပံ့အထောက်အထား|သုံးသပ်ချက်နှင့်နောက်မေးခွန်း|စီမံကိန်း|ဖန်တီး|ရလဒ်|အခြေခံနှိုင်းယှဉ်ချက်|ပြင်ဆင်ချက်|ကွာခြားချက်|ဖတ်ရှု|ကိုယ်တိုင်စစ်ဆေး|အဖြေစစ်ဆေး|ရှင်းလင်းချက်|အကြံပြုအခြေခံ|သင်ယူမှုတိုးတက်ခြင်း|ဝေါဟာရတံတား|ဘာသာစကား|အင်တာနက်မလို|အကောင့်|ဝင်ရောက်|စာရင်းသွင်း|ထွက်|အသုံးပြုသူအမည်|စကားဝှက်|သင်တန်း|သင်တန်းဝင်|ဝင်ရောက်ကုဒ်|စီမံကိန်းတင်သွင်း|တုံ့ပြန်ချက်|နောက်သို့|ရှေ့သို့|မှတ်တမ်းမရှိသေး|သိမ်းဆည်းပြီး|မပြီးစီးပါ|ကူးယူ|အစီရင်ခံစာဖတ်ရန်|ဆက်တင်'),
 'ta':('தமிழ்','OpenStudio · சீனா–ஆசியான்','முறையைப் புரிந்துகொள்ளுங்கள். உங்கள் விடையை உருவாக்குங்கள்.','Yucong Duan உருவாக்கிய DIKWP, பொருண்மை கணிதம் மற்றும் செயற்கை உணர்வு ஆய்வு முறைகளைக் கற்றுக்கொள்ளுங்கள். திறந்த களஞ்சியங்களைத் தேர்ந்து பரிசோதித்து தீர்வுகளை உருவாக்குங்கள்.',
'முகப்பு|கற்றல் வரைபடம்|களஞ்சிய வழிகாட்டி|பயிற்சிக் கூடங்கள்|திட்டப் பட்டறை|இணைந்து கற்றல்|ஆய்வு நூலகம்|புரிதலிலிருந்து படைப்பிற்கு|கற்கத் தொடங்கு|களஞ்சியங்களை ஆராய்|என் சிக்கல்|பாதையைப் பரிந்துரை|தேடு|அனைத்தும்|சிறப்புத் தேர்வுகள்|ஒப்பிடு|சேர்|நீக்கு|திற|மூலம்|உரிமம்|அனுபவம்|தேர்ந்தவை|நோக்கம் P|தரவு D|தகவல் I|அறிவு K|ஞானம் W|சோதனையை இயக்கு|சேமி|ஏற்றுமதி|இறக்குமதி|மீட்டமை|தலைப்பு|பயனாளி|நிபந்தனைகளும் வரம்புகளும்|நான் பெற்றவை|நான் மாற்றியவை|புதுமைக் கருதுகோள்|ஆதரவு ஆதாரம்|சிந்தனையும் அடுத்த கேள்வியும்|திட்டம்|உருவாக்கு|முடிவுகள்|அடிப்படை|திருத்தம்|வேறுபாடு|படி|சுய சோதனை|விடையைச் சரிபார்|விளக்கம்|பரிந்துரைக்கப்பட்ட முன்தேவைகள்|கற்றல் முன்னேற்றம்|கலைச்சொல் பாலம்|மொழி|இணையமின்றிப் பயன்படும்|கணக்கு|உள்நுழை|பதிவு செய்|வெளியேறு|பயனர்பெயர்|கடவுச்சொல்|பாடநெறி|பாடத்தில் சேர்|சேர்க்கைக் குறியீடு|திட்டத்தைச் சமர்ப்பி|பின்னூட்டம்|பின்செல்|அடுத்து|பதிவுகள் இல்லை|சேமிக்கப்பட்டது|செயல் முடியவில்லை|நகலெடு|அறிக்கை வாசிப்பு|அமைப்புகள்'),
 'tet':('Tetun','OpenStudio · Xina–ASEAN','Komprende métodu. Kria ita-nia resposta.','Aprende DIKWP, matemátika semántika no métodu konxiensia artifisiál husi Yucong Duan. Hili repositóriu nakloke, halo esperiénsia no kria solusaun.',
'Inísiu|Mapa aprendizajen|Bússola repositóriu|Laboratóriu|Estúdiu projetu|Aprende hamutuk|Biblioteka peskiza|Husi komprensaun ba kriasaun|Hahú aprende|Esplora repositóriu|Haʼu-nia problema|Sujere dalan|Buka|Hotu|Destaque|Kompara|Aumenta|Hasai|Loke|Fonte|Lisensa|Esperiénsia|Hili ona|Objetivu P|Dadus D|Informasaun I|Koñesimentu K|Sabedoria W|Halaʼo esperiénsia|Rai|Esporta|Importa|Reinísia|Títulu|Benefisiáriu|Kondisaun no limitasaun|Saida mak haʼu simu|Saida mak haʼu muda|Hipóteze inovasaun|Evidénsia apoiu|Reflesaun no pergunta tuir mai|Projetu|Kria|Rezultadu|Baze komparasaun|Revizaun|Diferensa|Lee|Teste rasik|Verifika resposta|Esplikasaun|Rekizitu rekomendadu|Progresu aprendizajen|Ponte terminolojia|Lian|Prontu offline|Konta|Tama|Rejista|Sai|Naran utilizadór|Liafuan-pase|Kursu|Tama kursu|Kódigu tama|Submete projetu|Komentáriu|Fila|Tuir mai|Seidauk iha rejistu|Rai ona|Asaun seidauk remata|Kopia|Lee relatóriu|Konfigurasaun')}
locales={}
for code,(name,brand,hero,desc,line) in rows.items():
 vals=line.split('|');assert len(vals)==len(keys),(code,len(vals),len(keys))
 locales[code]={'name':name,'brand':brand,'tagline':hero,'description':desc,**dict(zip(keys,vals))}
(R/'data/locales.json').write_text(json.dumps(locales,ensure_ascii=False,indent=2),encoding='utf-8')
print(len(locales),'languages;',len(keys),'shared interface labels')
